apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "greencompute-kafka-svc"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: greencompute-zookeeper-service:2181
        - name: KAFKA_CREATE_TOPICS
          value: "asset-topic:1:1"
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: greencompute-kafka
        ports:
        - containerPort: 9092
