apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: gc-zookeeper
    name: gc-zookeeper
    namespace: greencompute
spec:
    replicas: 5
    selector:
        matchLabels:
            app: zookeeper
    serviceName: gc-zookeeper-svc
    updateStrategy:
        type: RollingUpdate
    podManagementPolicy: Parallel
    template:
        metadata:
          labels:
            app: gc-zookeeper
        spec:
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: "app"
                              operator: In
                              values:
                              - gc-zookeeper
                        topologyKey: "kubernetes.io/hostname"
            containers:
            - name: greencompute-zookeeper
              image: "ibmcase/zookeeper:3.4.13"
              imagePullPolicy: Always
              ports:
              - containerPort: 2181
                name: client
                protocol: TCP
              - containerPort: 2888
                name: server
                protocol: TCP
              - containerPort: 3888
                name: leader-election
                protocol: TCP
              volumeMounts:
              - name: datadir
                mountPath: /var/lib/zookeeper
            readinessProbe:
              exec:
                command:
                - sh
                - -c
                - "zookeeper-ready 2181"
              initialDelaySeconds: 30
              timeoutSeconds: 5
            livenessProbe:
              exec:
                command:
                - sh
                - -c
                - "zookeeper-ready 2181"
              initialDelaySeconds: 30
              timeoutSeconds: 10
            securityContext:
                runAsUser: 1000
                fsGroup: 1000
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
