apiVersion: v1
kind: Service
metadata:
  labels:
    app: gc-zookeeper
  name: gc-client-zookeeper-svc
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  selector:
    app: gc-zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: gc-srv-zookeeper-svc
  labels:
    app: gc-zookeeper
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: gc-zookeeper
