apiVersion: v1
kind: Service
metadata:
  labels:
    app: gc-kafka
  name: gc-kafka-svc
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 32224
    nodePort: 32224
    targetPort: 32224
  selector:
    app: gc-kafka

# headless service to create dns record: gc-kafka-0.gc-kafka-hl-svc.greencompute.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: gc-kafka-hl-svc
  labels:
    app: gc-kafka
spec:
  ports:
  - port: 32224
    name: server
  clusterIP: None
  selector:
    app: gc-kafka
